# Site settings
title: "Grey Zone"
description: "A website for Hyoung Chul Kim"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Hyoung Chul Kim"
resume_title:                   "Ph.D Applicant for Fall 2024"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hchul.kim@yonsei.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "82-10-4748-0759"
resume_contact_address:         "Yonsei University"

resume_header_contact_info:     "Yonsei University • 82-10-4748-0759 • hchul.kim@yonsei.ac.kr"
display_header_contact_info:    "false"

resume_header_intro: "<p>MA student majoring in Economics. In broad sense, I am interested in symbiotic relations between socio-psychological factors (or infras) and economic behaviors.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
#resume_section_experience:      true
resume_section_interest:        true
resume_section_education:       true
resume_section_publications:    true
resume_section_working_papers:  true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/himakun"
  resume_twitter_url:           "http://twitter.com/HyoungChulKim1"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/hyoung-chul-kent-kim-b9a122232/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
